version: '3'
services:
    my-graphql-server:
        network_mode: 'host'

        build:
            context: ./server
        ports:
            - '5000:5000'
        container_name: my-graphql-server
        stdin_open: true

    my-next-js-app:
        network_mode: 'host'

        build:
            context: ./client
        ports:
            - '3000:3000'
        container_name: my-next-js-app
        stdin_open: true
# networks:
#     backend:
#         driver: host
